# Generated by Django 4.2.1 on 2024-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_product_category_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
