# Generated by Django 4.2.1 on 2024-05-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
