# Generated by Django 4.2.1 on 2024-04-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
    ]
