# Generated by Django 4.2.1 on 2024-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_basket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basket',
            name='product_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
