# Generated by Django 4.2.1 on 2024-04-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_basket_product_count_basket_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(default=None, max_length=20)),
                ('product_name', models.CharField(default=None, max_length=20)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
