# Generated by Django 4.2.1 on 2024-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='product_count',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='basket',
            name='product_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
