# Generated by Django 4.2.1 on 2024-05-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_basket_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
