# Generated by Django 4.2.1 on 2024-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_basket_basket_alter_basket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='id_product',
            field=models.IntegerField(default=0),
        ),
    ]
