# Generated by Django 4.2.1 on 2024-05-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_basket_id_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.AddField(
            model_name='basket',
            name='name',
            field=models.ManyToManyField(to='users.user'),
        ),
    ]
