# Generated by Django 4.2.1 on 2024-05-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_basket_id_product_basket_id_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.AddField(
            model_name='basket',
            name='id_product',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
