# Generated by Django 4.2.1 on 2024-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_basket_id_product_remove_basket_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='id_product',
            field=models.IntegerField(default=0),
        ),
    ]
