# Generated by Django 4.2.1 on 2024-05-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_basket_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
