# Generated by Django 4.2.1 on 2024-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_basket_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('score', models.IntegerField(default=3)),
                ('message', models.CharField(default=None, max_length=2000)),
            ],
        ),
    ]
