# Generated by Django 4.2.1 on 2024-05-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='id_product',
            field=models.IntegerField(default=0),
        ),
    ]
