# Generated by Django 4.2.1 on 2024-05-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_feedback_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='anonim',
            field=models.BooleanField(default=False),
        ),
    ]
