# Generated by Django 4.2.1 on 2024-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_registration',
            field=models.DateField(default=None),
        ),
    ]
