# Generated by Django 4.2.1 on 2024-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_data_registration_user_date_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hard_id',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
