# Generated by Django 4.2.1 on 2024-05-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_basket_hard_id_feedback_hard_id_alter_user_hard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='hard_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='hard_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
