# Generated by Django 4.2.1 on 2024-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_basket_hard_id_alter_feedback_hard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
