# Generated by Django 4.2.1 on 2024-06-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
