# Generated by Django 4.2.1 on 2024-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_userchocolate_additives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchocolate',
            name='additives',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userchocolate',
            name='basic',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userchocolate',
            name='chocolate',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userchocolate',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userchocolate',
            name='hard_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userchocolate',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
