# Generated by Django 4.2.1 on 2024-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_userchocolate_additives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchocolate',
            name='additives',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
