# Generated by Django 4.2.1 on 2024-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_userchocolate_additives'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchocolate',
            name='id_basket',
            field=models.IntegerField(default=0),
        ),
    ]
