# Generated by Django 4.2.1 on 2024-07-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_userchocolate_id_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchocolate',
            name='product_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
