# Generated by Django 4.2.1 on 2024-07-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_userchocolate_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_id', models.CharField(default=None, max_length=50)),
                ('id_product', models.IntegerField(default=0)),
                ('product_name', models.CharField(default=None, max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
