# Generated by Django 4.2.1 on 2024-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_basket_create_chocolate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUpdatePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_id', models.CharField(default=None, max_length=50)),
                ('new_password', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
