# Generated by Django 4.2.1 on 2024-08-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_newupdatepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newupdatepassword',
            name='count',
        ),
    ]
