# Generated by Django 4.2.1 on 2024-08-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_newupdatepassword_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
