# Generated by Django 4.2.1 on 2024-08-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='ava/'),
        ),
    ]
