# Generated by Django 4.2.1 on 2024-08-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_id', models.CharField(default=None, max_length=50)),
                ('image', models.ImageField(default=None, null=True, upload_to='feedback-img/')),
            ],
        ),
    ]
