# Generated by Django 4.2.1 on 2024-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_feedbackimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackimage',
            name='id_product',
            field=models.IntegerField(default=0),
        ),
    ]
