# Generated by Django 4.2.1 on 2024-08-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=None, max_length=11),
        ),
    ]
