# Generated by Django 4.2.1 on 2024-08-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.BooleanField(default=False),
        ),
    ]
