# Generated by Django 4.2.1 on 2024-08-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_feedback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
    ]
